default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password'} %>
  template: template0
  collation: ru_RU.UTF-8
  ctype: ru_RU.UTF-8

development:
  <<: *default
  database: oneirograms_development
  #username: oneirograms
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: oneirograms_test

production:
  <<: *default
  database: oneirograms
